CC = gcc
CFLAGS = -Wall -Wextra -Werror -pedantic

COMMON_SRC = socket_utils.c http_parser.c response.c todo.c

todo_api_0: todo_api_0.c $(COMMON_SRC)
	$(CC) $(CFLAGS) -o $@ todo_api_0.c $(COMMON_SRC)

todo_api_1: todo_api_1.c $(COMMON_SRC)
	$(CC) $(CFLAGS) -o $@ todo_api_1.c $(COMMON_SRC)

todo_api_2: todo_api_2.c $(COMMON_SRC)
	$(CC) $(CFLAGS) -o $@ todo_api_2.c $(COMMON_SRC)

todo_api_3: todo_api_3.c $(COMMON_SRC)
	$(CC) $(CFLAGS) -o $@ todo_api_3.c $(COMMON_SRC)

todo_api_4: todo_api_4.c $(COMMON_SRC)
	$(CC) $(CFLAGS) -o $@ todo_api_4.c $(COMMON_SRC)

todo_api_5: todo_api_5.c $(COMMON_SRC)
	$(CC) $(CFLAGS) -o $@ todo_api_5.c $(COMMON_SRC)
