CC = gcc
CFLAGS = -Wall -Werror -Wextra -pedantic -std=gnu89

all: strace_0 strace_1 strace_2 strace_3 strace_4 strace_5 strace_6 strace_7 strace_8

strace_0: strace_0.c
	$(CC) $(CFLAGS) strace_0.c -o strace_0

strace_1: strace_1.c
	$(CC) $(CFLAGS) strace_1.c -o strace_1

strace_2: strace_2.c
	$(CC) $(CFLAGS) strace_2.c -o strace_2

strace_3: strace_3.c
	$(CC) $(CFLAGS) strace_3.c -o strace_3

strace_4: strace_4.c
	$(CC) $(CFLAGS) strace_4.c -o strace_4

strace_5: strace_5.c
	$(CC) $(CFLAGS) strace_5.c -o strace_5

strace_6: strace_6.c
	$(CC) $(CFLAGS) strace_6.c -o strace_6

strace_7: strace_7.c
	$(CC) $(CFLAGS) strace_7.c -o strace_7

strace_8: strace_8.c
	$(CC) $(CFLAGS) strace_8.c -o strace_8

clean:
	rm -f strace_0 strace_1 strace_2 strace_3 strace_4 strace_5 strace_6 strace_7 strace_8
